### ISSUE TITLE
Consider giving `page_sidebar()` and `page_navbar()` main areas `min-width`

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#1040]
A rule like this is helpful to ensure that opening the sidebar doesn't overly squish the main content

```css
@media (min-width: 576px) {
  .bslib-page-sidebar > .bslib-sidebar-layout.html-fill-item > .main {
    min-width: max(576px, 100%);
  }
}
```

This rule isn't quite perfect because the scrolling happens across the entire content area and not the main sidebar area, but it's a reasonable starting place.

**Collapsed**

![image](https://github.com/rstudio/bslib/assets/5420529/b4dca96d-4c44-4bb8-8187-39740a3be7f6)

**Expanded, with rule**

![image](https://github.com/rstudio/bslib/assets/5420529/db9cf870-1cf4-4bc0-90b0-d43474338f94)

**Expanded, without rule**

![image](https://github.com/rstudio/bslib/assets/5420529/93b95dbe-d0a5-4770-80a8-06dc6a93aeb0)
