### ISSUE TITLE
`value_box()` style adjustments (top-right and value font size)

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#1041]
Two adjustments I've recently used in an app are:

1. Have the `value` of a `showcase_layout = "top right"` value box take up the entire value box width with

   ```css
   .bslib-value-box.showcase-top-right .value-box-grid .value-box-area {
     grid-column: 1 / 3;
   }
   ```

2. Use the container query width to drive the `value` font-size, rather than the viewport width (it currently uses something like `font-size: 1.325rem + .9vw`).

   ```css
   .bslib-value-box .value-box-value {
     font-size: calc(1rem + 3cqi);
   }
   ```

   With this rule, the width of the value box itself drives the font size of the value, so the value shrinks and grows proportional to the value box width.
