### ISSUE TITLE
Conditionally show content in full screen cards

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#1102]
## Feature request

It'd be nice to directly support conditionally shown content in full-screen cards. Here's how you can get there today.

1. Add conditional content in a `card_body()` with `class = "card-reveal-full-screen"`.

    ```r
	card(
	  "A fancy table",
	  card_body(
	    class = "card-reveal-full-screen",
	    reactableOutput("table")
	  ),
	  full_screen = TRUE
	)
	```

	The class can be named anything else (in case you think of a better name); what's important is that it's coupled with some custom CSS in the next step.

2. Use custom CSS to toggle the visibility of that card body area.

	```css
	.bslib-card[data-full-screen="false"] > .card-reveal-full-screen {
	  display: none;
	}
	```

	The above CSS hides elements with `.card-reveal-full-screen`, conveniently hiding the table output in the example above. By using `[data-full-screen="false"]` we also stay out of the way of the default presentation when in full-screen mode; in this case the `card_body()` around the table wants to have `display: flex`.

## Example app

Here's a [full example also available on shinylive.io/r](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw71OY4aIbM27RnCgFSUetTiyRAV1oACADwBaA6igBzOAH0AZtX0ATdiIMGCLF2-cGhYAEEDOygIAlYDdU04f1wfd09GJxt6IicOeN8CaihOTgMAXj9CLxNlADcVahM7XWpqzgJlCljM92VVKK0AeV1SVD7XMC6YsFlfAwE4iAna+ptG5pmigBUsAFUAUR8pnz5s3Sc4AGEAZVOhxKcyuEqoarmGprgKDAI8-1kdCE44RkrGMYzLUwqRaCR2HwBqRcAYiH1oQIDCAfPD+n0ACQjIEGZQQI6MLAqNQaLTsFEzXwdEnRdgwUiJTjjAwAX1kLJEIh4fFYAXQ7H0hQM+lhv3+fyFYoBsjALNw4Gg8CoVxudwedSeSzeeTwhBI5EoyAwUjEJiuwCcUHUNQ1JkWLwgBX8IWov38AF0DAA+AxvUoVKo2+p254UZE+Jy0TioHKsRAGCAkOAAbhEHIgsvdQA):

```r
library(shiny)
library(bslib)
library(reactable)

ui <- page_fluid(
  card(
    "A fancy table",
    card_body(
      class = "card-reveal-full-screen",
      reactableOutput("table")
    ),
    full_screen = TRUE
  ),
  includeCSS("card-reveal-full-screen.css")
)

server <- function(input, output) {
  output$table <- renderReactable({
    reactable(mtcars)
  })
}

shinyApp(ui = ui, server = server)
```

```css
/* card-reveal-full-screen.css */
.bslib-card[data-full-screen="false"] > .card-reveal-full-screen {
  display: none;
}
```

**Comment by gadenbuie** [comment]
Also worth noting: there's a way to do this using the `input${card_id}_full_screen` reactive. I think there is room for both approaches, especially because the server-managed hiding is a little cumbersome. (See rstudio/htmltools#434.)

**Comment by gadenbuie** [comment]
The same approach works for value boxes but requires more complicated CSS:

```css
.bslib-value-box[data-full-screen="false"] > .card-body > .value-box-area > .card-reveal-full-screen,
.bslib-value-box[data-full-screen="false"] > .card-body > .value-box-grid > .value-box-area > .card-reveal-full-screen {
  display: none;
}
```

[Example app](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw71OY4aIbM27RnCgFSUetTiyRAV1oACADwBaA6igBzOAH0AZtX0ATdiIMGAblEe36RAB6uEO7uQmAwpAQsnGG4biGcqIx8pHauYACkTgZRjDF4BhCMRADu7BG5nAICccEhuU42fk4c8SE51FCcnAYAvAZhDSbKHirUJna61OOcBMoUsW0hyqrqmnAA8rqkqNvpa1phsu01SzylUZxwfQZStMQQnIiIUjb3JOm5E8VkE7TTR1q7XOJUutk6rCI2xuILBNi0dlINgIFHIjHYJVoTlI3HsU2oNlm82C-TCAEYAAwU1D+QFLSbTQlzOAUG4AFSwAFUAKLxU51PgERxOOAAYQAyuLPiwnMM4KNvBN8SYiSyIBgCN0jiIdI84IxRoxjGZJhA1LQPnxdqRcAYoTttgIDCB4vbrQASA7XUwGZQQEWMLAqNQaLTsF11dwrEPrcqRaLHAwAX1kSZEIh4fFYAEF0Ox9Dd9Largb9TD9YbZGAk7hwNB4FQhiMxkrpirmRQNd08IQSORKMgMFIxCYGsAnFB1K2Zh2IL0wnZvFcwgBdAwAPgMGplcoV4wZM+JzviTloiQhiEKJDgAG4RGmICIh9IGCYvD4TH5-OPJ1Bp+3iXnMBF2oZcwDXTdt0YWVmlYDct3fXQ4E-AITBYFR4Kg2Vm0VA8ALVWpnxHRDkK-H8pzw1UKCAkCwIgrchlgzCSJQ-wTEsZJskglivzQlZMKbeUW0o2djzqU9zygVhLwga87wgB9qxXIA):

```r
library(shiny)
library(bslib)
library(reactable)

ui <- page_fluid(
  value_box(
    "mtcars",
    sprintf("%d cars", nrow(mtcars)),
    card_body(
      class = "card-reveal-full-screen",
      reactableOutput("table")
    ),
    showcase = bsicons::bs_icon("car-front-fill"),
    showcase_layout = showcase_left_center(width_full_screen = "100px"),
    full_screen = TRUE
  ),
  includeCSS("card-reveal-full-screen.css")
)

server <- function(input, output) {
  output$table <- renderReactable({
    reactable(mtcars)
  })
}

shinyApp(ui = ui, server = server)
```
