### ISSUE TITLE
Brand: Support typography font family shortcuts

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#1172]
The following `_brand.yml` fails (well, doesn't work out as expected) with `bs_theme()`

```yaml
typography:
  fonts:
    - family: Barrio
      source: google
    - family: Roboto
      source: google
  base: Roboto
  headings: Barrio
```

but should be treated as equivalent to

```yaml
typography:
  fonts:
    - family: Barrio
      source: google
    - family: Roboto
      source: google
  base: 
    family: Roboto
  headings: 
    family: Barrio
```
