### ISSUE TITLE
Potentially add more opinionated pre/code styles

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#126]
BS4 dropped a lot of them, and @hadley has suggested:

```css
pre {
  word-wrap: normal;
  word-break: normal;
  border: 1px solid #eee;
  padding: 0.5em;
}
pre, code {
  background-color: #f8f8f8;
  color: #222;
}
pre code {
  overflow: auto;
  word-wrap: normal;
  white-space: pre;
}
```
