### ISSUE TITLE
safari renders a credentials dialog for numericInput() in bs_theme_preview()

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#229]
This also seems to be a problem for vanilla shiny, see that with:

```r
shiny::shinyAppDir(system.file("themer-demo", package = "bslib"))
```

<img width="1134" alt="Screen Shot 2021-01-16 at 7 44 31 PM" src="https://user-images.githubusercontent.com/1365941/104847843-c0102b80-58a7-11eb-993a-62bc37631031.png">

**Comment by cpsievert** [comment]
Also, it appears Firefox also wants to think that the `numericInput()` is some sort of password

<img width="1284" alt="Screen Shot 2021-01-16 at 8 00 45 PM" src="https://user-images.githubusercontent.com/1365941/104848017-ade2bd00-58a8-11eb-935c-e7c9648185e5.png">

**Comment by cpsievert** [comment]
Here's a minimal example:

```r
library(shiny)
ui <- fluidPage(
  numericInput("foo", "number", value = 0),
  passwordInput("bar", "password", "fo"))
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by cpsievert** [comment]
Seems we could do something like this

```css
input[type="number"]::-webkit-contacts-auto-fill-button {
  visibility: hidden;
  display: none !important;
  pointer-events: none;
  position: absolute;
  right: 0;
}
```

https://stackoverflow.com/a/39885072/1583084
