### ISSUE TITLE
Inconsistent styles between 3 and 4

### ISSUE THREAD

**Issue by atusy** [rstudio/bslib#240]
This issue is transferred from 

- <https://github.com/rstudio/rmarkdown/issues/2015#issuecomment-765355398>
- <https://github.com/rstudio/rmarkdown/pull/2019>

The problems are

- Blockquotes are missing border line on the left.
  I suggest the rule below, inheriting Bootstrap 3.
  I omitted specifying color so that it is themable.
  In Bootstrap 3, border width also changes by themes, but maybe not in Bootstrap 4.

```css
blockquote {
    padding: 10.5px 21px;
    margin: 0 0 21px;
    border-left: 5px solid;
}
```

- Code blocks with long lines scroll. I'm fine if this is the design choice. Just let developers know Bootstrap 3 applies

```css
pre code { white-space: pre-wrap }
```

- With Bootstrap 4, first line of code block has extra padding on the left. Bootstrap 3 avoids this by

```css
pre code {padding: 0}
```
