### ISSUE TITLE
error when using bs_themer() in R Markdown

### ISSUE THREAD

**Issue by maelle** [rstudio/bslib#247]
I tried using the R Markdown document shown in slide 17 of https://talks.cpsievert.me/20201215/rstudio-global.pdf and got an error from Shiny. 

```r
`bslib::bs_themer()` requires `shiny::bootstrapLib()` to be present in the app's UI. Consider providing `bslib::bs_theme()` to the theme argument of the relevant page layout function (or, more generally, adding `bootstrapLib(bs_theme())` to the UI.
```

I changed the R Markdown document to:

````md
---
title: "Untitled"
html_document:
  theme: !expr bslib::bs_theme()
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
bslib::bs_themer()
```

blablabla

````

which didn't help.

**Comment by cpsievert** [comment]
The `html_document` needs to be under a top-level `output`, like this:

```yaml
---
title: "Untitled"
output:
  html_document:
    theme: !expr bslib::bs_theme()
runtime: shiny
---
```
