### ISSUE TITLE
simplify yaml front matter when used in Rmd to provide fonts

### ISSUE THREAD

**Issue by cderv** [rstudio/bslib#256]
Currently, the way to provide some fonts is to use specific function when you want google fonts for example. 
This lead to this type of Rmd header
```yaml
   theme:
      base_font: !expr bslib::font_google("Prompt")
      code_font: !expr bslib::font_google("JetBrains Mono")
```

For now, we manage to avoid the use of `!expr` for basic feature and keep it for only advanced customisation (most of the time undocumented). Mainly because it is not easy to write, understand and it is a bit confusing with inline knitr code chunk. 

I would love to be able to write this instead
```yaml
   theme:
      base_font: 
        google: Prompt
      code_font: 
        google: JetBrains Mono
```
or 
```yaml
   theme:
     base_font: 
       google: 
         family: Prompt
         wght: "200..900"
```

Fonts is something that I believe users will want to modify easily and having a more YAML like syntax not relying on `!expr` would be nice. 

cc @yihui
