### ISSUE TITLE
rpivotTable: Dropdown list problem when passing bs_theme()'s options

### ISSUE THREAD

**Issue by gd047** [rstudio/bslib#300]
The little arrow icons near the [rpivotTable](https://cran.r-project.org/web/packages/rpivotTable/vignettes/rpivotTableIntroduction.html)'s grouping categories, that open the dropdown selection lists, do not work when using bslib's bootstrap 4 themes in rmarkdown

However, there is no problem with the aggregators or renderers dropdown arrows. 

**NOT working**

```
---
output:
  html_document:
    theme:
      version: 4
      bootswatch: minty
---
```

That works OK

```
---
output:
  html_document:
    theme: flatly
---
```
