### ISSUE TITLE
Allow adding multiple local font-styles with bs_theme & font_face

### ISSUE THREAD

**Issue by markschat** [rstudio/bslib#376]
Hi, 
either I can´t figure it out, or it is not possible as of now.
I´m not able to pass more than one style from a font-family to bs_theme (e.g normal, bold, italic from 'Open Sans').

**Reprex**
```r
library(shiny)
library(bslib)
library(htmltools)

# Borrow fonts from bslib ----
addResourcePath("fonts", system.file("fonts", package = "bslib"))

# Define font collection ----
nunito <- font_collection(
  font_face("Nunito", weight = 400, style = "normal", src = "url('../fonts/XRXV3I6Li01BKof4MQ.woff')"),
  font_face("Nunito", weight = 700, style = "normal", src = "url('../fonts/XRXW3I6Li01BKofAjsOkZQ.woff')")
)

ui <- fluidPage(
  theme = bs_theme(base_font = nunito),
  tags$p("Normal Text"),
  tags$b("Bold Text (seems bold, but is thickened by browser I suppose)"),
)
shinyApp(ui, \(...){})
```

As I inspect this app via the browser dev-tools, I can see this CSS declaration (`../_Nunito-0.4.0/font.css`):

```css
@font-face {
  font-family: Nunito;
  src: url('../fonts/XRXV3I6Li01BKof4MQ.woff');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}
```

My font is included 🎉 but only the first style (weight 400) -> bold/700 is missing. Here´s what I would expect in the file:
```css
@font-face {
  font-family: Nunito;
  src: url('../fonts/XRXV3I6Li01BKof4MQ.woff');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: Nunito;
  src: url('../fonts/XRXW3I6Li01BKofAjsOkZQ.woff');
  font-weight: 700;
  font-style: normal;
  font-display: swap;
}
```

The browser still produces a thickened text (reprex), but I think this is some browser-magic and not the months of work the font designer put into developing the bold style as it is missing in the font-face declaration.
