### ISSUE TITLE
Google font files in directory that Github Pages ignores by default

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/bslib#408]
## Describe the problem

When using google fonts, the CSS and woff files are placed in a directory beginning with  an underscore. This is by default ignored by Github Pages when building the site unless a `.nojekyll` file is present.

This is quite difficult to debug - if serving from a `/docs` folder, all one can is see a mysterious 404 error on `font.css` with the file present at the relevant path in the repo. 

Would it make sense to have it placed in a directory not beginning in an underscore, assuming `{bslib}` has control over this?

My YAML header is set as follows, with `{bslib}` installed from Github.

```yaml
output:
  html_document:
    theme:
      version: 5
      bg: "#ffffff"
      fg: "#000000"
      headings_color: blue
      primary: "#0000ff"
      navbar-bg: "#0000ff"
      base_font:
        google: "IBM Plex Sans"
      code_font:
        google: "IBM Plex Mono"
```
The font CSS and woff end up in "site-files/_IBM Plex Mono-0.4.0".
