### ISSUE TITLE
Collapsed sidebar in a card may have undesired height

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#518]
I noticed that under certain conditions the sidebar height may grow as it transitions into the collapsed state. When that happens, it might also then have that height while collapsed, causing the parent container to grow.

https://user-images.githubusercontent.com/5420529/227639335-2ce47175-6da7-40c1-a326-b1587341adb9.mp4

The case above comes from a very basic example:

```r
card(
  card_header("Card with sidebar"),
  layout_sidebar(
    sidebar = sidebar("Card Sidebar"),
    "My card"
  ),
  card_footer("footer of said card")
)
```

Given the collapsed and transitioning sidebar `height: 0` might be better?

https://user-images.githubusercontent.com/5420529/227641609-c8d0f940-87e0-4cde-a6a7-53f919c9d065.mp4

But I'm not sure what other ramifications that might have. Here's what I was testing in the second screengrab:

```css
.bslib-sidebar-layout.sidebar-collapsed > .sidebar {
	height: 0;
}
.bslib-sidebar-layout.transitioning > .sidebar {
	height: 0;
	overflow: hidden;
}
```
