### ISSUE TITLE
Disable page-level fillable containers in `page_*()` functions at small screen heights?

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#673]
We switch off fillable containers for small screen widths, but page-level fill containers are similarly constrained on small screen heights. 

We could disable page-level fillability for small screen heights with a media query like this

```css
@media screen and (max-height: 799px) {
  .bslib-page-fill.html-fill-container {
    display: block;
  }
}
```

https://github.com/rstudio/bslib/assets/5420529/4709a3b9-fbad-4631-8320-b0af75ec6bf9
