### ISSUE TITLE
Shiny preset: Increase slider bar target area

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#688]
- [ ] Ensure that target area for clicking on the slider bar is large enough
- ~Adjust margin/padding between line and play button~
- [x] Review sliders in context of https://github.com/rstudio/shinycoreci/tree/main/inst/apps/005-sliders

**Comment by gadenbuie** [comment]
The problem is that we need to increase the size of the `.irs-line` span, which will require some JavaScript changes to add an inner element that becomes the touch target:

```html
<!-- from this -->
<span class="irs-line" tabindex="0"></span>

<!-- to this -->
<span class="irs-line" tabindex="0">
  <span class="irs-touch-fix"></span>
</span>
```

with associated CSS

```cs
.irs-touch-fix {
    display: block;
    position: absolute;
    width: 100%;
    height: 20px;
    top: -10px;
    bottom: 10px;
    z-index: 1; /* raise above ticks and labels */
}
```

**Comment by gadenbuie** [comment]
## Slider Animate Button

```scss
.slider-animate-container {
  text-align: left;
  
  .slider-animate-button {
    opacity: 1;
  }
}

.irs--shiny.irs-with-grid ~ .slider-animate-container {
  margin-top: -5px;
}

.irs--shiny:not(.irs-with-grid) ~ .slider-animate-container {
  margin-top: 5px;
}
```
