### ISSUE TITLE
Shiny preset: slider animation button

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#689]
```scss
.slider-animate-container {
  text-align: left;
  
  .slider-animate-button {
    opacity: 1;
  }
}

.irs--shiny.irs-with-grid ~ .slider-animate-container {
  margin-top: -5px;
}

.irs--shiny:not(.irs-with-grid) ~ .slider-animate-container {
  margin-top: 5px;
}
```

<img src="https://github.com/rstudio/bslib/assets/5420529/a12dee91-5213-4602-803a-122d8ff87bae" alt="image" width="48%">
<img src="https://github.com/rstudio/bslib/assets/5420529/a4da0c74-6356-4c0f-8564-a21d9f26093f" alt="image" width="48%">

_Originally posted by @gadenbuie in https://github.com/rstudio/bslib/issues/688#issuecomment-1638727825_
