### ISSUE TITLE
Bottom margin of fill items in fillable containers

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#732]
And most specifically for items with the `bslib-mb-spacing` class. We're probably covered in most cases by `bslib-gap-spacing` on the parent, but we also generally as a default posture won't want margin bottom on activated fill items.

```css
// Remove bslib margin bottom spacing for fill items in a fillable container
.html-fill-container > .html-fill-item.bslib-mb-spacing {
  margin-bottom: 0;
}
```

See https://github.com/rstudio/bslib/pull/725#discussion_r1284845168 for some additional context
