### ISSUE TITLE
Un-scope CSS variables where possible

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#751]
Currently, we scope our custom CSS properties to the component's primary CSS class, taking a page from Bootstrap's playbook.

```css
.bslib-sidebar-layout {
  --bslib-sidebar-fg: ...;
  --bslib-sidebar-bg: ...;
  --bslib-sidebar-column-main: ...;
}
```

Some of these variables are for internal use, such as `--bslib-sidebar-column-main`, and others we anticipate being useful to users or other frameworks, such as `--bslib-sidebar-fg`.

I think we should consider moving the globally-useful properties to `:root` and prefix locally-scoped variables with an underscore.

```css
:root {
  --bslib-sidebar-fg: ...;
  --bslib-sidebar-bg: ...;
}

.bslib-sidebar-layout {
  --_bslib-sidebar-column-main: ...;
}
```
